import { useCallback, useEffect, useRef, useState } from 'react'
import { fetchAuthor, fetchCommunityPage, fetchCommunityPost, fetchOwnProfile, hideCommunityPost, saveOwnProfile, type PostCard as PostCardData, type PostDetail, type PostType, type PublicAuthor, type PublicProfile } from '../../api/community'
import { fetchOwnPosts, withdrawPost, type OwnerPostCard, type PostStatus } from '../../api/publishing'
import type { Account } from '../../api/auth'
import { usePagedList } from '../../hooks/usePagedList'
import { Dialog } from '../../components/Dialog'
import { useDialog } from '../../components/dialogContext'
import { PublicationDocument } from './PublicationDocument'
import { AttachmentImage } from './AttachmentMedia'
import { useToast } from '../../components/toastContext'
import { Author, Button, CommunityIcon, Empty, FeedTabs, Heading, LoadState, Notice, Pager } from './ui'
import { dateLabel, errorMessage, typeLabels } from './model'

const silentError = () => undefined
export function PostCard({ post }: { post: PostCardData }) {
  const thumbnail = post.type === 'BLOG' ? post.attachments.find(attachment => attachment.kind === 'IMAGE' && attachment.state === 'READY') : undefined
  return <article className="card post-card" data-post-id={post.id}><div className="post-heading"><Author author={post.author} subtitle={`${dateLabel(post.firstPublishedAt)} · 站内可见`} /><span className={`badge ${post.type === 'MOMENT' ? '' : 'purple'}`}>{typeLabels[post.type]}</span></div><div className="post-inner"><div className="post-copy">{post.title ? <h2><a href={`#/community/posts/${post.id}`}>{post.title}</a></h2> : <div className="untitled-spacer" />}<p className="excerpt">{post.summary.slice(0, 135)}{post.summary.length > 135 ? '…' : ''}</p></div>{thumbnail && <div className="paper-thumb"><AttachmentImage attachment={thumbnail} context={{ postId: post.id, owner: false }} /></div>}</div>{post.type === 'DAILY' && <div className="mini-checklist">{post.summary.split('\n').filter(line => line.startsWith('- ')).slice(0, 2).map((line, index) => <span key={index}><CommunityIcon name="check" />{line.slice(2)}</span>)}</div>}<div className="post-foot"><span className="flex"><CommunityIcon name={post.type === 'DAILY' ? 'calendar' : 'report'} />{post.type === 'DAILY' ? `${post.businessDate} 的进展` : post.type === 'BLOG' ? '长文阅读' : '一点发现'}{post.attachments.length > 0 && <span>{post.attachments.length} 个附件</span>}</span><a className="text-link" href={`#/community/posts/${post.id}`}>阅读全文 <CommunityIcon name="arrow-right" /></a></div></article>
}

export function CommunityFeed({ account, authorId }: { account: Account; authorId?: string }) {
  const [type, setType] = useState<PostType | ''>(''); const [page, setPage] = useState(0)
  const [author, setAuthor] = useState<PublicAuthor | null>(null); const [authorError, setAuthorError] = useState<string | null>(null)
  const [authorUnavailable, setAuthorUnavailable] = useState(false); const [authorAttempt, setAuthorAttempt] = useState(0)
  const [draft, setDraft] = useState<OwnerPostCard | null>(null)
  const query = useCallback((signal: AbortSignal) => fetchCommunityPage(type, authorId, page, signal), [type, authorId, page])
  const list = usePagedList(query, silentError, setPage)
  useEffect(() => {
    const controller = new AbortController()
    if (authorId) void fetchAuthor(authorId, controller.signal).then(setAuthor).catch((caught: unknown) => { if (!controller.signal.aborted) { setAuthorError(errorMessage(caught)); setAuthorUnavailable((caught as { status?: number }).status === 404) } })
    else void fetchOwnPosts('DRAFT', 0, controller.signal).then(result => setDraft(result.items[0] ?? null)).catch(() => undefined)
    return () => controller.abort()
  }, [authorId, authorAttempt])
  if (authorUnavailable) return <Unavailable />
  if (authorError) return <LoadState loading={false} error={authorError} retry={() => { setAuthorError(null); setAuthorAttempt(value => value + 1) }} />
  return <>{authorId ? <><a className="back-link" href="#/community"><CommunityIcon name="arrow-left" />返回广场</a>{author ? <div className="card profile-hero"><div className="avatar big">{author.nickname.slice(0, 1)}</div><div><div className="eyebrow">MEMBER PROFILE</div><h1>{author.nickname}</h1><p>{author.bio}</p><span className="badge">站内主页 · 仅展示已发布内容</span></div></div> : <LoadState loading error={null} retry={() => undefined} />}</> : <Heading eyebrow="COMMUNITY" title="让每一点进展，被看见" description="分享今天的收获，写下值得留下的经验。" />}<div className="columns"><section>{!authorId && <div className="card composer"><div className="author"><div className="avatar"><CommunityIcon name="edit" /></div><div><strong>今天，有什么值得分享？</strong><p>你的工作记录始终私有，只有确认发布的内容才会出现在这里。</p></div></div><div className="composer-actions"><a className="btn soft" href="#/publishing/sources"><CommunityIcon name="calendar" />分享今天</a><a className="btn secondary" href="#/publishing/new/MOMENT"><CommunityIcon name="edit" />发动态</a><a className="btn secondary" href="#/publishing/new/BLOG"><CommunityIcon name="notebook" />写博客</a></div></div>}<FeedTabs value={type} onChange={next => { setType(next); setPage(0) }} /><LoadState loading={list.loading} error={list.error} retry={() => void list.refresh()} />{!list.loading && !list.error && <div className="feed-list">{list.data?.items.length ? list.data.items.map(post => <PostCard key={post.id} post={post} />) : <Empty title={authorId ? '这里还没有已发布内容' : '让第一份分享，从你开始'} description={authorId ? '私有工作记录与草稿不会出现在这个主页。' : '工作记录仍然私有。选一小段值得分享的进展就好。'}>{!authorId && <a className="btn" href="#/publishing/new">开始分享</a>}</Empty>}</div>}{list.data && <Pager page={page} totalPages={list.data.totalPages} total={list.data.totalElements} onPage={setPage} loading={list.loading} />}</section><aside className="aside-sticky community-aside">{draft && !authorId && <div className="card side-card"><h3 className="flex"><CommunityIcon name="report" />继续写下去</h3><span className="badge">草稿 · 仅自己可见</span><h3 className="side-draft-title">{draft.title || '未命名草稿'}</h3><p>{typeLabels[draft.type]}</p><div className="rule" /><a className="arrow-link" href={`#/publishing/posts/${draft.postId}`}>继续编辑 <CommunityIcon name="arrow-right" /></a></div>}<div className="card side-card"><h3>{authorId ? '这里展示什么？' : '一个有边界的分享空间'}</h3><p>{authorId ? '作者选择的昵称、简介与已发布内容。不展示私有任务、工作日历或实时在线状态。' : '内容仅本站登录用户可见。发布前，检查记录、图片与附件中是否有不适合分享的信息。'}</p>{(!authorId || authorId === account.id) && <><div className="rule" /><a className="arrow-link" href="#/publishing">管理我的发布 <CommunityIcon name="arrow-right" /></a></>}</div><div className="side-caption">这里没有热榜或互动计数。<br />按发布时间，安静地阅读。</div></aside></div></>
}

export function Unavailable({ message }: { message?: string }) { return <div className="login-wrap"><Empty title="内容暂不可访问" description={message ?? '内容可能已撤回、下架，或当前账号没有访问权限。这里不会回显原内容。'} /><div className="unavailable-action"><a className="btn secondary" href="#/community">返回广场</a></div></div> }

export function CommunityDetail({ id, account }: { id: string; account: Account }) {
  const { notify, toastRef } = useToast<HTMLSpanElement>()
  const [post, setPost] = useState<PostDetail | null>(null); const [error, setError] = useState<string | null>(null); const [unavailable, setUnavailable] = useState(false); const [attempt, setAttempt] = useState(0)
  const [copyLink, setCopyLink] = useState<string | null>(null); const dialog = useDialog()
  useEffect(() => {
    const controller = new AbortController()
    void fetchCommunityPost(id, controller.signal).then(setPost).catch((caught: unknown) => { if (!controller.signal.aborted) { setError(errorMessage(caught)); setUnavailable((caught as { status?: number }).status === 404) } })
    return () => controller.abort()
  }, [id, attempt])
  const copy = async () => { const link = `${window.location.origin}${window.location.pathname}#/community/posts/${id}`; try { await navigator.clipboard.writeText(link); notify('站内链接已复制', 'success') } catch { setCopyLink(link) } }
  const hide = async () => {
    if (!post) return
    const accepted = await dialog({ className: 'community-dialog', title: '下架这篇内容？', description: '下架后成员不能读取正文与附件，作者不能重新发布。请输入下架理由。', input: { label: '下架理由', value: '', maxLength: 1000 }, danger: true, confirmLabel: '确认下架', onConfirm: async reason => { await hideCommunityPost(id, post.revisionId, reason) } })
    if (accepted) { setPost(null); setUnavailable(true) }
  }
  if (unavailable) return <Unavailable />
  if (!post) return <LoadState loading={!error} error={error} retry={() => { setError(null); setAttempt(value => value + 1) }} />
  return <><a className="back-link" href="#/community"><CommunityIcon name="arrow-left" />返回广场</a><div className="columns reading-layout"><section><PublicationDocument value={post} attachments={post.attachments} author={post.author} context={{ postId: id, owner: false }} published={post} footer={<span ref={toastRef}><Button className="secondary sm" onClick={() => void copy()}><CommunityIcon name="copy" />复制站内链接</Button></span>} />{account.role === 'ADMIN' && <div className="reader-admin-actions"><Button className="danger" onClick={() => void hide()}>管理员下架</Button></div>}{post.author.id === account.id && <a className="btn secondary mobile-reader-edit" href={`#/publishing/posts/${id}`}>编辑这篇内容</a>}</section><aside className="aside-sticky reading-aside"><div className="card side-card"><div className="avatar big">{post.author.nickname.slice(0, 1)}</div><h3 className="side-author-title">{post.author.nickname}</h3><p>{post.author.bio}</p><div className="rule" /><a className="arrow-link" href={`#/community/authors/${post.author.id}`}>查看作者主页 <CommunityIcon name="arrow-right" /></a></div><div className="card side-card"><h3>文章脉络</h3><div className="toc">{post.bodyMarkdown.split('\n').filter(line => /^#{1,3} /.test(line)).map((line, index) => <button key={index} type="button" onClick={() => document.querySelectorAll('.prose :is(h1,h2,h3)')[index]?.scrollIntoView({ block: 'start' })}>{line.replace(/^#+ /, '')}</button>)}</div></div><div className="side-caption">发布者可以撤回内容。<br />已下载的文件副本无法收回。</div>{post.author.id === account.id && <a className="btn secondary" href={`#/publishing/posts/${id}`}>编辑这篇内容</a>}</aside></div>{copyLink && <Dialog className="community-dialog" titleId="copy-link-title" busy={false} onClose={() => setCopyLink(null)}><div className="dialog"><h2 id="copy-link-title">站内链接已准备好</h2><p>此链接仅供本站登录成员访问。</p><input data-dialog-autofocus readOnly aria-label="站内链接" value={copyLink} onFocus={event => event.target.select()} /><div className="dialog-actions"><Button onClick={() => setCopyLink(null)}>知道了</Button></div></div></Dialog>}</>
}

export function MyPublications() {
  const [status, setStatus] = useState<PostStatus | ''>(''); const [page, setPage] = useState(0); const [profileOpen, setProfileOpen] = useState(false)
  const query = useCallback((signal: AbortSignal) => fetchOwnPosts(status, page, signal), [status, page]); const list = usePagedList(query, silentError, setPage); const dialog = useDialog()
  const withdraw = async (post: OwnerPostCard) => {
    const accepted = await dialog({ className: 'community-dialog', title: '撤回这篇内容？', description: '撤回后，广场和作者主页不再展示该内容，新的读者请求也不能读取正文或附件。已复制、截图或下载的副本无法收回。', danger: true, confirmLabel: '确认撤回', onConfirm: async () => { await withdrawPost(post.postId, post.version) } })
    if (accepted) void list.refresh()
  }
  return <><Heading eyebrow="YOUR WRITING" title="我的发布" description="草稿留给自己，发布给站内成员；每一步都由你决定。" extra={<div className="flex wrap"><Button className="secondary" onClick={() => setProfileOpen(true)}>编辑公开资料</Button><a className="btn" href="#/publishing/new"><CommunityIcon name="plus" />新建内容</a></div>} /><div className="columns"><section className="card"><div className="manage-top"><div className="tabs" aria-label="发布状态">{([['', '全部'], ['DRAFT', '草稿'], ['PUBLISHED', '已发布'], ['WITHDRAWN', '已撤回']] as const).map(([value, label]) => <button key={value} type="button" className={`tab ${status === value ? 'active' : ''}`} aria-pressed={status === value} onClick={() => { setStatus(value); setPage(0) }}>{label}</button>)}</div></div><LoadState loading={list.loading} error={list.error} retry={() => void list.refresh()} /><div className="manage-list">{!list.loading && !list.error && (list.data?.items.length ? list.data.items.map(post => <article className="manage-row" key={post.postId} data-manage-id={post.postId}><div className="spread"><span className={`badge ${post.status === 'PUBLISHED' ? 'green' : post.status === 'DRAFT' ? 'purple' : ''}`}>{{ DRAFT: '草稿 · 仅自己可见', PUBLISHED: '已发布 · 站内可见', WITHDRAWN: '已撤回 · 读者不可见', HIDDEN: '已下架 · 读者不可见' }[post.status]}</span><span className="subtle">{typeLabels[post.type]}</span></div><h2>{post.title || post.summary.slice(0, 35) || '未命名草稿'}</h2><p>{post.hasUnpublishedChanges ? '你有一份尚未公开的修改稿。读者仍看到上次发布的版本。' : post.status === 'DRAFT' ? '还没有发布。正文和附件只有你能看到。' : post.status === 'WITHDRAWN' ? '已从广场移除。重新整理后，可以预览并再次发布。' : post.status === 'HIDDEN' ? `内容已被下架，作者不能绕过下架重新发布。${post.moderation ? `理由：${post.moderation.reason}` : ''}` : '修改后先保存草稿，确认发布更新才会对读者生效。'}</p><div className="manage-row-footer"><span className="subtle">{dateLabel(post.updatedAt)}{post.currentRevisionNo ? ` · 发布版本 v${post.currentRevisionNo}` : ''}</span><div className="manage-actions"><a className="btn secondary sm" href={`#/publishing/posts/${post.postId}`}><CommunityIcon name="edit" />{post.status === 'HIDDEN' ? '维护私有草稿' : post.status === 'PUBLISHED' ? '编辑修改稿' : '继续编辑'}</a>{post.status === 'PUBLISHED' && <><a className="btn ghost sm" href={`#/community/posts/${post.postId}`}>查看发布版</a><Button className="danger sm" onClick={() => void withdraw(post)}>撤回</Button></>}</div></div></article>) : <Empty title="还没有这类内容" description="从一段轻量的分享开始。"><a className="btn" href="#/publishing/new">开始分享</a></Empty>)}</div>{list.data && <Pager page={page} totalPages={list.data.totalPages} total={list.data.totalElements} onPage={setPage} loading={list.loading} />}</section><aside className="aside-sticky manage-aside"><div className="card side-card"><h3>保存 ≠ 发布</h3><p>手动保存只影响私有草稿。<br />发布更新后，正文与附件才一起切换。</p><div className="rule" /><h3>撤回之后</h3><p>新的读者请求不再取得内容或附件。已被复制、截图或下载的副本无法收回。</p></div></aside></div>{profileOpen && <ProfileDialog onClose={() => setProfileOpen(false)} />}</>
}

function ProfileDialog({ onClose }: { onClose: () => void }) {
  const [profile, setProfile] = useState<PublicProfile | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const pending = useRef(false)
  useEffect(() => { const controller = new AbortController(); void fetchOwnProfile(controller.signal).then(setProfile).catch((caught: unknown) => { if (!controller.signal.aborted) setError(errorMessage(caught)) }); return () => controller.abort() }, [])
  const save = async () => { if (!profile || pending.current) return; pending.current = true; setBusy(true); setError(null); try { await saveOwnProfile(profile); onClose() } catch (caught) { setError(errorMessage(caught)) } finally { pending.current = false; setBusy(false) } }
  return <Dialog className="community-dialog" titleId="profile-edit-title" busy={busy} onClose={onClose}><div className="dialog"><h2 id="profile-edit-title">编辑公开资料</h2><p>仅昵称和简介会展示给本站成员，不公开登录用户名。</p>{profile && <form onSubmit={event => { event.preventDefault(); void save() }}><label>公开昵称<input autoFocus data-dialog-autofocus value={profile.nickname} disabled={busy} required maxLength={40} onChange={event => setProfile({ ...profile, nickname: event.target.value })} /></label><label>简介<textarea value={profile.bio} disabled={busy} maxLength={500} onChange={event => setProfile({ ...profile, bio: event.target.value })} /></label>{error && <Notice kind="error">{error}</Notice>}<div className="dialog-actions"><Button className="secondary" disabled={busy} onClick={onClose}>取消</Button><Button type="submit" disabled={busy}>{busy ? '正在保存…' : '保存公开资料'}</Button></div></form>}{!profile && <LoadState loading={!error} error={error} retry={() => { setError(null); void fetchOwnProfile().then(setProfile).catch((caught: unknown) => setError(errorMessage(caught))) }} />}</div></Dialog>
}
